<?php

namespace Database\Seeders;

use App\Models\TimeZone;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TimeZoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // TimeZone::truncate();

        $timeZones = [
            [ 'country_id' => 1, 'timezone' => 'Asia/Kabul', 'gmt_offset' => 'GMT +04:30'],
            [ 'country_id' => 2, 'timezone' => 'Europe/Tirane', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 3, 'timezone' => 'Africa/Algiers', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 4, 'timezone' => 'Pacific/Pago_Pago', 'gmt_offset' => 'GMT -11:00'],
            [ 'country_id' => 5, 'timezone' => 'Europe/Andorra', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 6, 'timezone' => 'Africa/Luanda', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 7, 'timezone' => 'America/Anguilla', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/Casey', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/Davis', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/DumontDUrville', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/Mawson', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/McMurdo', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/Palmer', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/Rothera', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/Syowa', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/Troll', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 8, 'timezone' => 'Antarctica/Vostok', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 18, 'timezone' => 'America/Antigua', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Cordoba', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Jujuy', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/La_Rioja', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Mendoza', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Rio_Gallegos', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Salta', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/San_Juan', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/San_Luis', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Tucuman', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Ushuaia', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Buenos_Aires', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 19, 'timezone' => 'America/Argentina/Catamarca', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 31, 'timezone' => 'Asia/Yerevan', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 32, 'timezone' => 'America/Aruba', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 33, 'timezone' => 'Antarctica/Macquarie', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Adelaide', 'gmt_offset' => 'GMT +09:30'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Brisbane', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Broken_Hill', 'gmt_offset' => 'GMT +09:30'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Darwin', 'gmt_offset' => 'GMT +09:30'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Eucla', 'gmt_offset' => 'GMT +08:45'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Hobart', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Lindeman', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Lord_Howe', 'gmt_offset' => 'GMT +10:30'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Melbourne', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Perth', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 33, 'timezone' => 'Australia/Sydney', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 45, 'timezone' => 'Europe/Vienna', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 46, 'timezone' => 'Asia/Baku', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 47, 'timezone' => 'America/Nassau', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 48, 'timezone' => 'Asia/Bahrain', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 49, 'timezone' => 'Asia/Dhaka', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 50, 'timezone' => 'America/Barbados', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 51, 'timezone' => 'Europe/Minsk', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 52, 'timezone' => 'Europe/Brussels', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 53, 'timezone' => 'America/Belize', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 54, 'timezone' => 'Africa/Porto-Novo', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 55, 'timezone' => 'Atlantic/Bermuda', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 56, 'timezone' => 'Asia/Thimphu', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 57, 'timezone' => 'America/La_Paz', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 58, 'timezone' => 'America/Kralendijk', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 59, 'timezone' => 'Europe/Sarajevo', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 60, 'timezone' => 'Africa/Gaborone', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Araguaina', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Bahia', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Belem', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Boa_Vista', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Campo_Grande', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Cuiaba', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Eirunepe', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Fortaleza', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Maceio', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Manaus', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Noronha', 'gmt_offset' => 'GMT -02:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Porto_Velho', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Recife', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Rio_Branco', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Santarem', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 61, 'timezone' => 'America/Sao_Paulo', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 77, 'timezone' => 'Indian/Chagos', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 78, 'timezone' => 'Asia/Brunei', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 79, 'timezone' => 'Europe/Sofia', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 80, 'timezone' => 'Africa/Ouagadougou','gmt_offset' => 'GMT'],
            [ 'country_id' => 81, 'timezone' => 'Africa/Bujumbura', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 82, 'timezone' => 'Asia/Phnom_Penh', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 83, 'timezone' => 'Africa/Douala', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Blanc-Sablon', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Cambridge_Bay', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Creston', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Dawson', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Dawson_Creek', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Edmonton', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Fort_Nelson', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Glace_Bay', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Goose_Bay', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Halifax', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Inuvik', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Iqaluit', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Moncton', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Rankin_Inlet', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Regina', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Resolute', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 84, 'timezone' => 'America/St_Johns', 'gmt_offset' => 'GMT -02:30'],
            [ 'country_id' => 84, 'timezone' => 'America/Swift_Current', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Toronto', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Vancouver', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Whitehorse', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Winnipeg', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 84, 'timezone' => 'America/Atikokan', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 107, 'timezone' => 'Atlantic/Cape_Verde', 'gmt_offset' => 'GMT -01:00'],
            [ 'country_id' => 108, 'timezone' => 'America/Cayman', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 109, 'timezone' => 'Africa/Bangui', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 110, 'timezone' => 'Africa/Ndjamena', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 111, 'timezone' => 'America/Punta_Arenas', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 111, 'timezone' => 'America/Santiago', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 111, 'timezone' => 'Pacific/Easter', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 114, 'timezone' => 'Asia/Shanghai', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 114, 'timezone' => 'Asia/Urumqi', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 116, 'timezone' => 'Indian/Christmas', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 117, 'timezone' => 'Indian/Cocos', 'gmt_offset' => 'GMT +06:30'],
            [ 'country_id' => 118, 'timezone' => 'America/Bogota', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 119, 'timezone' => 'Indian/Comoro', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 120, 'timezone' => 'Africa/Brazzaville', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 121, 'timezone' => 'Africa/Kinshasa', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 121, 'timezone' => 'Africa/Lubumbashi', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 123, 'timezone' => 'Pacific/Rarotonga', 'gmt_offset' => 'GMT -10:00'],
            [ 'country_id' => 124, 'timezone' => 'America/Costa_Rica', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 125, 'timezone' => 'Europe/Zagreb', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 126, 'timezone' => 'America/Havana', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 128, 'timezone' => 'Asia/Famagusta', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 128, 'timezone' => 'Asia/Nicosia', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 130, 'timezone' => 'Europe/Prague', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 132, 'timezone' => 'Europe/Copenhagen', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 133, 'timezone' => 'Africa/Djibouti', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 134, 'timezone' => 'America/Dominica', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 135, 'timezone' => 'America/Santo_Domingo', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 136, 'timezone' => 'America/Guayaquil', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 136, 'timezone' => 'Pacific/Galapagos', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 138, 'timezone' => 'Africa/Cairo', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 139, 'timezone' => 'America/El_Salvador', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 140, 'timezone' => 'Africa/Malabo', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 141, 'timezone' => 'Africa/Asmara', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 142, 'timezone' => 'Europe/Tallinn', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 143, 'timezone' => 'Africa/Addis_Ababa', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 144, 'timezone' => 'Atlantic/Stanley', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 145, 'timezone' => 'Atlantic/Faroe', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 146, 'timezone' => 'Pacific/Fiji', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 147, 'timezone' => 'Europe/Helsinki', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 148, 'timezone' => 'Europe/Paris', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 149, 'timezone' => 'America/Cayenne', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 150, 'timezone' => 'Pacific/Marquesas', 'gmt_offset' => 'GMT -09:30'],
            [ 'country_id' => 150, 'timezone' => 'Pacific/Tahiti', 'gmt_offset' => 'GMT -10:00'],
            [ 'country_id' => 150, 'timezone' => 'Pacific/Gambier', 'gmt_offset' => 'GMT -09:00'],
            [ 'country_id' => 153, 'timezone' => 'Indian/Kerguelen', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 154, 'timezone' => 'Africa/Libreville', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 155, 'timezone' => 'Africa/Banjul','gmt_offset' => 'GMT'],
            [ 'country_id' => 156, 'timezone' => 'Asia/Tbilisi', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 157, 'timezone' => 'Europe/Berlin', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 157, 'timezone' => 'Europe/Busingen', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 159, 'timezone' => 'Africa/Accra','gmt_offset' => 'GMT'],
            [ 'country_id' => 160, 'timezone' => 'Europe/Gibraltar', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 161, 'timezone' => 'Europe/Athens', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 162, 'timezone' => 'America/Danmarkshavn','gmt_offset' => 'GMT'],
            [ 'country_id' => 162, 'timezone' => 'America/Nuuk', 'gmt_offset' => 'GMT -02:00'],
            [ 'country_id' => 162, 'timezone' => 'America/Scoresbysund','gmt_offset' =>'GMT'],
            [ 'country_id' => 162, 'timezone' => 'America/Thule', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 166, 'timezone' => 'America/Grenada', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 167, 'timezone' => 'America/Guadeloupe', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 168, 'timezone' => 'Pacific/Guam', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 169, 'timezone' => 'America/Guatemala', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 170, 'timezone' => 'Europe/Guernsey', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 171, 'timezone' => 'Africa/Conakry','gmt_offset' => 'GMT'],
            [ 'country_id' => 172, 'timezone' => 'Africa/Bissau','gmt_offset' => 'GMT'],
            [ 'country_id' => 173, 'timezone' => 'America/Guyana', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 174, 'timezone' => 'America/Port-au-Prince', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 175, 'timezone' => 'Europe/Vatican', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 176, 'timezone' => 'America/Tegucigalpa', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 177, 'timezone' => 'Asia/Hong_Kong', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 178, 'timezone' => 'Europe/Budapest', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 179, 'timezone' => 'Atlantic/Reykjavik','gmt_offset' => 'GMT'],
            [ 'country_id' => 180, 'timezone' => 'Asia/Kolkata', 'gmt_offset' => 'GMT +05:30'],
            [ 'country_id' => 181, 'timezone' => 'Asia/Makassar', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 181, 'timezone' => 'Asia/Pontianak', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 181, 'timezone' => 'Asia/Jakarta', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 181, 'timezone' => 'Asia/Jayapura', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 185, 'timezone' => 'Asia/Tehran', 'gmt_offset' => 'GMT +03:30'],
            [ 'country_id' => 186, 'timezone' => 'Asia/Baghdad', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 187, 'timezone' => 'Europe/Dublin', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 188, 'timezone' => 'Europe/Isle_of_Man', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 189, 'timezone' => 'Asia/Jerusalem', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 190, 'timezone' => 'Europe/Rome', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 191, 'timezone' => 'America/Jamaica', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 192, 'timezone' => 'Asia/Tokyo', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 193, 'timezone' => 'Europe/Jersey', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 194, 'timezone' => 'Asia/Amman', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 195, 'timezone' => 'Asia/Almaty', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 195, 'timezone' => 'Asia/Aqtau', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 195, 'timezone' => 'Asia/Aqtobe', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 195, 'timezone' => 'Asia/Atyrau', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 195, 'timezone' => 'Asia/Oral', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 195, 'timezone' => 'Asia/Qostanay', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 195, 'timezone' => 'Asia/Qyzylorda', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 202, 'timezone' => 'Africa/Nairobi', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 203, 'timezone' => 'Pacific/Kanton', 'gmt_offset' => 'GMT +13:00'],
            [ 'country_id' => 203, 'timezone' => 'Pacific/Kiritimati', 'gmt_offset' => 'GMT +14:00'],
            [ 'country_id' => 203, 'timezone' => 'Pacific/Tarawa', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 206, 'timezone' => 'Asia/Pyongyang', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 207, 'timezone' => 'Asia/Seoul', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 208, 'timezone' => 'Asia/Kuwait', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 209, 'timezone' => 'Asia/Bishkek', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 210, 'timezone' => 'Asia/Vientiane', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 211, 'timezone' => 'Europe/Riga', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 212, 'timezone' => 'Asia/Beirut', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 213, 'timezone' => 'Africa/Maseru', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 214, 'timezone' => 'Africa/Monrovia','gmt_offset' => 'GMT'],
            [ 'country_id' => 215, 'timezone' => 'Africa/Tripoli', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 216, 'timezone' => 'Europe/Vaduz', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 217, 'timezone' => 'Europe/Vilnius', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 218, 'timezone' => 'Europe/Luxembourg', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 219, 'timezone' => 'Asia/Macau', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 220, 'timezone' => 'Europe/Skopje', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 221, 'timezone' => 'Indian/Antananarivo', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 222, 'timezone' => 'Africa/Blantyre', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 223, 'timezone' => 'Asia/Kuala_Lumpur', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 223, 'timezone' => 'Asia/Kuching', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 225, 'timezone' => 'Indian/Maldives', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 226, 'timezone' => 'Africa/Bamako','gmt_offset' => 'GMT'],
            [ 'country_id' => 227, 'timezone' => 'Europe/Malta', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 228, 'timezone' => 'Pacific/Kwajalein', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 228, 'timezone' => 'Pacific/Majuro', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 230, 'timezone' => 'America/Martinique', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 231, 'timezone' => 'Africa/Nouakchott','gmt_offset' => 'GMT'],
            [ 'country_id' => 232, 'timezone' => 'Indian/Mauritius', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 233, 'timezone' => 'Indian/Mayotte', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Bahia_Banderas', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Cancun', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Chihuahua', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Ciudad_Juarez', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Hermosillo', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Matamoros', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Mazatlan', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Merida', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Mexico_City', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Monterrey', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Ojinaga', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 234, 'timezone' => 'America/Tijuana', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 246, 'timezone' => 'Pacific/Kosrae', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 246, 'timezone' => 'Pacific/Pohnpei', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 246, 'timezone' => 'Pacific/Chuuk', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 249, 'timezone' => 'Europe/Chisinau', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 250, 'timezone' => 'Europe/Monaco', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 251, 'timezone' => 'Asia/Choibalsan', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 251, 'timezone' => 'Asia/Hovd', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 251, 'timezone' => 'Asia/Ulaanbaatar', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 254, 'timezone' => 'Europe/Podgorica', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 255, 'timezone' => 'America/Montserrat', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 256, 'timezone' => 'Africa/Casablanca', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 256, 'timezone' => 'Africa/El_Aaiun', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 258, 'timezone' => 'Africa/Maputo', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 259, 'timezone' => 'Asia/Yangon', 'gmt_offset' => 'GMT +06:30'],
            [ 'country_id' => 260, 'timezone' => 'Africa/Windhoek', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 261, 'timezone' => 'Pacific/Nauru', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 262, 'timezone' => 'Asia/Kathmandu', 'gmt_offset' => 'GMT +05:45'],
            [ 'country_id' => 263, 'timezone' => 'Europe/Amsterdam', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 264, 'timezone' => 'Pacific/Noumea', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 265, 'timezone' => 'Pacific/Auckland', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 265, 'timezone' => 'Pacific/Chatham', 'gmt_offset' => 'GMT +12:45'],
            [ 'country_id' => 267, 'timezone' => 'America/Managua', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 268, 'timezone' => 'Africa/Niamey', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 269, 'timezone' => 'Africa/Lagos', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 270, 'timezone' => 'Pacific/Niue', 'gmt_offset' => 'GMT -11:00'],
            [ 'country_id' => 271, 'timezone' => 'Pacific/Norfolk', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 272, 'timezone' => 'Pacific/Saipan', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 273, 'timezone' => 'Europe/Oslo', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 274, 'timezone' => 'Asia/Muscat', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 275, 'timezone' => 'Asia/Karachi', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 276, 'timezone' => 'Pacific/Palau', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 277, 'timezone' => 'Asia/Gaza', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 277, 'timezone' => 'Asia/Hebron', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 279, 'timezone' => 'America/Panama', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 280, 'timezone' => 'Pacific/Bougainville', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 280, 'timezone' => 'Pacific/Port_Moresby', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 282, 'timezone' => 'America/Asuncion', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 283, 'timezone' => 'America/Lima', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 284, 'timezone' => 'Asia/Manila', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 285, 'timezone' => 'Pacific/Pitcairn', 'gmt_offset' => 'GMT -08:00'],
            [ 'country_id' => 286, 'timezone' => 'Europe/Warsaw', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 287, 'timezone' => 'Atlantic/Azores','gmt_offset' => 'GMT'],
            [ 'country_id' => 287, 'timezone' => 'Atlantic/Madeira', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 287, 'timezone' => 'Europe/Lisbon', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 290, 'timezone' => 'America/Puerto_Rico', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 291, 'timezone' => 'Asia/Qatar', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 292, 'timezone' => 'Europe/Bucharest', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 293, 'timezone' => 'Europe/Astrakhan', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 293, 'timezone' => 'Europe/Kaliningrad', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 293, 'timezone' => 'Europe/Kirov', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 293, 'timezone' => 'Europe/Moscow', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 293, 'timezone' => 'Europe/Samara', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 293, 'timezone' => 'Europe/Saratov', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 293, 'timezone' => 'Europe/Ulyanovsk', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 293, 'timezone' => 'Europe/Volgograd', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Anadyr', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Barnaul', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Chita', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Irkutsk', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Kamchatka', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Khandyga', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Krasnoyarsk', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Magadan', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Novokuznetsk', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Novosibirsk', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Omsk', 'gmt_offset' => 'GMT +06:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Sakhalin', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Srednekolymsk', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Tomsk', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Ust-Nera', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Vladivostok', 'gmt_offset' => 'GMT +10:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Yakutsk', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 293, 'timezone' => 'Asia/Yekaterinburg', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 319, 'timezone' => 'Africa/Kigali', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 322, 'timezone' => 'Atlantic/St_Helena','gmt_offset' => 'GMT'],
            [ 'country_id' => 323, 'timezone' => 'America/St_Kitts', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 324, 'timezone' => 'America/St_Lucia', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 325, 'timezone' => 'America/Marigot', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 326, 'timezone' => 'America/Miquelon', 'gmt_offset' => 'GMT -02:00'],
            [ 'country_id' => 327, 'timezone' => 'America/St_Vincent', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 328, 'timezone' => 'Pacific/Apia', 'gmt_offset' => 'GMT +13:00'],
            [ 'country_id' => 329, 'timezone' => 'Europe/San_Marino', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 330, 'timezone' => 'Africa/Sao_Tome','gmt_offset' => 'GMT'],
            [ 'country_id' => 331, 'timezone' => 'Asia/Riyadh', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 332, 'timezone' => 'Africa/Dakar','gmt_offset' =>  'GMT'],
            [ 'country_id' => 333, 'timezone' => 'Europe/Belgrade', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 334, 'timezone' => 'Indian/Mahe', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 335, 'timezone' => 'Africa/Freetown','gmt_offset' => 'GMT'],
            [ 'country_id' => 336, 'timezone' => 'Asia/Singapore', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 337, 'timezone' => 'America/Lower_Princes', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 338, 'timezone' => 'Europe/Bratislava', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 339, 'timezone' => 'Europe/Ljubljana', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 340, 'timezone' => 'Pacific/Guadalcanal', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 341, 'timezone' => 'Africa/Mogadishu', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 342, 'timezone' => 'Africa/Johannesburg', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 343, 'timezone' => 'Atlantic/South_Georgia', 'gmt_offset' => 'GMT -02:00'],
            [ 'country_id' => 344, 'timezone' => 'Africa/Juba', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 345, 'timezone' => 'Africa/Ceuta', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 345, 'timezone' => 'Atlantic/Canary', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 345, 'timezone' => 'Europe/Madrid', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 348, 'timezone' => 'Asia/Colombo', 'gmt_offset' => 'GMT +05:30'],
            [ 'country_id' => 349, 'timezone' => 'Africa/Khartoum', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 350, 'timezone' => 'America/Paramaribo', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 351, 'timezone' => 'Arctic/Longyearbyen', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 352, 'timezone' => 'Africa/Mbabane', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 353, 'timezone' => 'Europe/Stockholm', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 354, 'timezone' => 'Europe/Zurich', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 355, 'timezone' => 'Asia/Damascus', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 356, 'timezone' => 'Asia/Taipei', 'gmt_offset' => 'GMT +08:00'],
            [ 'country_id' => 357, 'timezone' => 'Asia/Dushanbe', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 358, 'timezone' => 'Africa/Dar_es_Salaam', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 359, 'timezone' => 'Asia/Bangkok', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 360, 'timezone' => 'Asia/Dili', 'gmt_offset' => 'GMT +09:00'],
            [ 'country_id' => 361, 'timezone' => 'Africa/Lome','gmt_offset' => 'GMT'],
            [ 'country_id' => 362, 'timezone' => 'Pacific/Fakaofo', 'gmt_offset' => 'GMT +13:00'],
            [ 'country_id' => 363, 'timezone' => 'Pacific/Tongatapu', 'gmt_offset' => 'GMT +13:00'],
            [ 'country_id' => 364, 'timezone' => 'America/Port_of_Spain', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 365, 'timezone' => 'Africa/Tunis', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 366, 'timezone' => 'Europe/Istanbul', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 367, 'timezone' => 'Asia/Ashgabat', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 368, 'timezone' => 'America/Grand_Turk', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 369, 'timezone' => 'Pacific/Funafuti', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 370, 'timezone' => 'Africa/Kampala', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 371, 'timezone' => 'Europe/Kyiv', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 371, 'timezone' => 'Europe/Simferopol', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 373, 'timezone' => 'Asia/Dubai', 'gmt_offset' => 'GMT +04:00'],
            [ 'country_id' => 374, 'timezone' => 'Europe/London', 'gmt_offset' => 'GMT +01:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Boise', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Chicago', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Denver', 'gmt_offset' => 'GMT -06:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Detroit', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Indiana/Indianapolis', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Indiana/Knox', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Indiana/Marengo', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Indiana/Petersburg', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Indiana/Tell_City', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Indiana/Vevay', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Indiana/Vincennes', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Indiana/Winamac', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Juneau', 'gmt_offset' => 'GMT -08:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Kentucky/Louisville', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Kentucky/Monticello', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Los_Angeles', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Menominee', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Metlakatla', 'gmt_offset' => 'GMT -08:00'],
            [ 'country_id' => 375, 'timezone' => 'America/New_York', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Nome', 'gmt_offset' => 'GMT -08:00'],
            [ 'country_id' => 375, 'timezone' => 'America/North_Dakota/Beulah', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 375, 'timezone' => 'America/North_Dakota/Center', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 375, 'timezone' => 'America/North_Dakota/New_Salem', 'gmt_offset' => 'GMT -05:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Phoenix', 'gmt_offset' => 'GMT -07:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Sitka', 'gmt_offset' => 'GMT -08:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Yakutat', 'gmt_offset' => 'GMT -08:00'],
            [ 'country_id' => 375, 'timezone' => 'Pacific/Honolulu', 'gmt_offset' => 'GMT -10:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Adak', 'gmt_offset' => 'GMT -09:00'],
            [ 'country_id' => 375, 'timezone' => 'America/Anchorage', 'gmt_offset' => 'GMT -08:00'],
            [ 'country_id' => 404, 'timezone' => 'Pacific/Midway', 'gmt_offset' => 'GMT -11:00'],
            [ 'country_id' => 404, 'timezone' => 'Pacific/Wake', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 406, 'timezone' => 'America/Montevideo', 'gmt_offset' => 'GMT -03:00'],
            [ 'country_id' => 407, 'timezone' => 'Asia/Samarkand', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 407, 'timezone' => 'Asia/Tashkent', 'gmt_offset' => 'GMT +05:00'],
            [ 'country_id' => 409, 'timezone' => 'Pacific/Efate', 'gmt_offset' => 'GMT +11:00'],
            [ 'country_id' => 410, 'timezone' => 'America/Caracas', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 411, 'timezone' => 'Asia/Ho_Chi_Minh', 'gmt_offset' => 'GMT +07:00'],
            [ 'country_id' => 412, 'timezone' => 'America/Tortola', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 413, 'timezone' => 'America/St_Thomas', 'gmt_offset' => 'GMT -04:00'],
            [ 'country_id' => 414, 'timezone' => 'Pacific/Wallis', 'gmt_offset' => 'GMT +12:00'],
            [ 'country_id' => 415, 'timezone' => 'Asia/Aden', 'gmt_offset' => 'GMT +03:00'],
            [ 'country_id' => 416, 'timezone' => 'Africa/Lusaka', 'gmt_offset' => 'GMT +02:00'],
            [ 'country_id' => 417, 'timezone' => 'Africa/Harare', 'gmt_offset' => 'GMT +02:00'],
        ];

        foreach ($timeZones as $timeZone) {
            TimeZone::create($timeZone);
        }
    
    }
}
